### ISSUE TITLE
Set zh-TW as default branch.

### ISSUE THREAD

**Issue by appleboy** [neighborhood999/bash-handbook#6]
剛進來這邊看到 master branch 找不到翻譯檔案，要不要把 `zh-TW` 設定為 default branch

並且在首頁 readme 寫上翻譯的檔案路徑。

👍

**Comment by neighborhood999** [comment]
@appleboy 感謝！作者請我們修改完小部份就可以 merge 到 master 去了，到時候同步後就會看到 zh-TW 的翻譯了！

**Comment by appleboy** [comment]
OK
